### PR TITLE
#73 Fix inconsistent Sidebar/Top Navigation dropdown behavior 

### LINKED ISSUE #73: Inconsistent sidebar/top navigation dropdown behavior
## Basic information

* Tiller version: 1..3.0
* Module: menu

## Bug description

Dropdowns defined in topRightAction prop of Sidebar Navigation and Top Navigation are being opened/closed on every click
instead of only toggling when clicking on a dropdown icon.

### Expected behavior

Dropdowns close and open only when clicking on the dropdown buttons.

### Actual behavior

Dropdowns are toggling on every click of the dropdown component.

### PR DESCRIPTION
**Pull request by fbeceic**
## Basic information

* Tiller version: 1.3.0
* Module: menu

## Bug description

Top Navigation and Sidebar Navigation's dropdown components are being opened/closed on every click. 
Deeper context passing and communication between subcomponents is required in order to correctly detect wheter
the dropdowns are closed or opened and fix this issue.

### Related issue

Closes #73 

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added a story to cover my changes
- [x] All new and existing story tests pass

### CODE REVIEW

File: libs/theme/src/defaultTheme.tsx [hunk 1]
```diff
@@ -1446,9 +1446,9 @@ const defaultComponentConfig = {
       dark: "text-white bg-slate-800",
       light: "text-slate-700 bg-white border-b border-slate-200",
       default: "text-white bg-primary-dark",
-      padding: "py-4 px-3",
+      padding: "p-4 md:py-4 md:px-3",
```
Comment (jtomic-croz) [inline libs/theme/src/defaultTheme.tsx:1449]: `md:py-4` is unnecessary

File: libs/menu/src/NavigationContextProvider.tsx [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+
+type NavigationDropdownContext = {
+  small?: boolean;
+  isMenuOpened: boolean;
+  isActionOpened: boolean;
+  onActionOpenedToggle?: (opened: boolean) => void;
+  onMenuOpenedToggle?: (opened: boolean) => void;
+};
+
+export const NavigationDropdownContext = createNamedContext<NavigationDropdownContext>("NavigationDropdownContext", {
```
Comment (jtomic-croz) [inline libs/menu/src/NavigationContextProvider.tsx:20]: See if it makes sense to name this NavigationContext.

**Review by jtomic-croz — APPROVED** [review]
