### PR TITLE
#17 Fix Example App

### LINKED ISSUE #17: Tiller Example App
## Basic information

* Tiller version: 1.0.1
* Module: project

## Enhancement description

In apps/example, create a working test app which uses Tiller components. Use Vite app setup.

### Current behaviour

Example app is not working correctly.

### Wanted behaviour

Tiller Test App (Vite) based on Tiller components.

### PR DESCRIPTION
**Pull request by ivam5**
## Basic information

* Tiller version: 1.0.1
* Module: project

### Summary

Tiller Test App (Vite) based on Tiller components.

### Related issue

Closes #17 

## Types of changes

- Enhancement (non-breaking change which enhances existing functionality)

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added a story to cover my changes
- [x] All new and existing story tests pass

### CODE REVIEW

**Review by fbeceic — APPROVED** [review]

File: apps/example/src/App.tsx [hunk 1]
```diff
@@ -0,0 +1,111 @@
+import React from "react";
+
+import { Button, Card, Container, PageHeading } from "@tiller-ds/core";
+import { DescriptionList } from "@tiller-ds/data-display";
+import { CheckboxGroup, Input, RadioGroup, Textarea } from "@tiller-ds/form-elements";
+import { Icon } from "@tiller-ds/icons";
+import { Intl } from "@tiller-ds/intl";
+
+function App() {
+  const candidatesHelp = "Lorem ipsum dolor sit amet. Lorem ipsum.";
```
Comment (jtomic-croz) [inline apps/example/src/App.tsx:10]: I'm not sure if this is necessary. Either have them in translations, or directly as prop without additional const
