### PR TITLE
#134 - Fix logo condition in Login component

### LINKED ISSUE #134: Login component won't render children if logo is present
## Basic information

* Tiller version: 1.7.0
* Module: Login

## Bug description

Children in the login component don't render when the logo prop is defined.

### Expected behavior

Render children if logo is present.

### PR DESCRIPTION
**Pull request by ivam5**
## Basic information

* Tiller version: 1.7.0
* Module: Login

### Related issue

Closes #134 

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added a story to cover my changes
- [x] All new and existing story tests pass

### CODE REVIEW

File: libs/patterns/src/Login.tsx [hunk 1]
```diff
@@ -139,16 +139,14 @@ export default function Login({
...
                         </div>
-                      ) : (
-                        <>
-                          {children}
-                          <h1 className={tokens.headerContainer}>{<Intl name={title || "login.labels.header"} />}</h1>
-                        </>
-                      )}
+                        )
+                      }
+                        {children}
```
Comment (jtomic-croz) [inline libs/patterns/src/Login.tsx:148]: align indentation please

**Review by jtomic-croz — APPROVED** [review]
