### PR TITLE
#160 Fix `visibleItemCount` consistency for `DropdownMenu` component

### LINKED ISSUE #160: `DropdownMenu` - `visibleItemCount` prop problems
## Basic information

* Tiller version:
  1.7.3

## Bug description

 If `visibleItemCount` is set to a length larger then the length of the items the height appears as if there are that many items inside the menu:
image

Also, when the `visibleItemCount` is updated from its initial value, the component doesn't update its state to the newer value, but rather resorts to the initial one.

### Expected behavior

The component adjusts its height properly and updates its state if the prop `visibleItemCount` changes.

### Actual behavior

The component doesn't account for edge cases and sometimes sets its height wrong. Also, it doesn't track the `visibleItemCount` prop properly.

### PR DESCRIPTION
**Pull request by fbeceic**
## Basic information

* Tiller version: 1.7.3
* Module: menu

## Description

Fixed `visibleItemCount` prop consistency when changing values for `DropdownMenu` component.

### Related issue

Closes #160 

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added a story to cover my changes
- [x] All new and existing story tests pass

### CODE REVIEW

File: libs/menu/src/DropdownMenu.tsx [hunk 1]
```diff
@@ -252,17 +257,27 @@ function DropdownMenuContainer({
     // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [childrenContainerRef.current]);
 
+  const getHeight = useCallback(() => {
```
Comment (jtomic-croz) [inline libs/menu/src/DropdownMenu.tsx:260]: Why not useMemo instead of useCallback? I don't see a reason that this needs to be callable

**Review by jtomic-croz — APPROVED** [review]
