### PR TITLE
#13 Fix reversed expander icons

### LINKED ISSUE #13: Top Navigation mobile view item expander icons reversed
## Basic information

* Tiller version: 1.0.1

* Module: menu

## Bug description

Expander icon is reversed on mobile view. Arrow up icon is shown when item is not expanded while arrow down icon 
is shown when an item is expanded. Icons should be reversed.

### Expected behavior

Arrow down icon is present when item is not expanded, arrow up icon is present when item is expanded.

### Actual behavior

Arrow up icon is present when item is not expanded, arrow down icon is present when item is expanded.

### PR DESCRIPTION
**Pull request by fbeceic**
## Basic information

* Tiller version: 1.0.1
* Module: menu

## Bug description

Expander icon is reversed on mobile view. Arrow up icon is shown when item is not expanded while arrow down icon
is shown when an item is expanded. Icons should be reversed.

### Related issue

Closes #13 

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added a story to cover my changes
- [x] All new and existing story tests pass

### CODE REVIEW

File: libs/menu/src/TopNavigation.tsx [hunk 1]
```diff
@@ -438,7 +438,7 @@ export function TopNavigationItem({
           <div className="flex flex-col flex-wrap items-center">
             <Link {...props} to={to || "#"} className={cn + ` items-center`} onClick={() => setOpened(!opened)}>
               {title}
-              {opened ? expanderCloseIcon : expanderOpenIcon}
+              {opened ? expanderOpenIcon : expanderCloseIcon}
```
Comment (jtomic-croz) [inline libs/menu/src/TopNavigation.tsx:441]: This seems like the old condition was ok, but icons were reversed. `expanderOpen` should be the one that is shown when user needs to open the dropdown/card/collapse, not when it's already opened

**Review by jtomic-croz — CHANGES_REQUESTED** [review]

File: libs/core/src/Card.tsx [hunk 2]
```diff
@@ -166,8 +166,8 @@ function CardHeader({ className = "", removeSpacing = false, children, ...props
     }
   };
 
-  const expanderOpenIcon = useIcon("expanderOpen", props.expanderOpenIcon, { className: "ml-2", size: 3 });
-  const expanderCloseIcon = useIcon("expanderClose", props.expanderCloseIcon, { className: "ml-2", size: 3 });
+  const expanderOpenIcon = useIcon("openExpander", props.expanderOpenIcon, { className: "ml-2", size: 3 });
```
Comment (jtomic-croz) [inline libs/core/src/Card.tsx:169]: Can you also rename all the usages to match the icon name?
eg: `const openExpanderIcon = useIcon("openExpander", ...

**Review by ivam5 — DISMISSED** [review]

**Review by jtomic-croz — APPROVED** [review]
