### PR TITLE
#36 Improve Top Navigation Responsiveness

### LINKED ISSUE #15: Progress Bar - completed icon and sizing
## Basic information

* Tiller version: 1.0.1

* Module: core

## Bug description

Progress Bar component behaves strange when a lot of steps are defined, margins and padding are off and need to 
be adjusted.
Also, completed check icon is not rendering properly.

### Expected behavior

Appropriate padding on the left and right sides of the step. Check icon present when step is completed.

### Actual behavior

Inconsistent padding on the left and right sides of a step. Left size padding behaves normally but right padding is inconsistent.
Completed step is colored blue and check icon is not rendering inside it.

### LINKED ISSUE #36: Top Navigation responsiveness
## Basic information

* Tiller version: 1.0.2

* Module: menu

## Bug description

Top Navigation's dropdown menu isn't behaving properly on small screens (mobile display). The dropdown icon, when expanded, goes off screen on smaller screens.

### Expected behavior

Dropdown menu icon expands with proper width and padding on the sides, similar to the behaviour on the Sidebar Navigation.

### Actual behavior

Inconsistent width and side padding when dropdown is expanded on smaller screens.

### PR DESCRIPTION
**Pull request by fbeceic**
## Basic information

* Tiller version: 1.0.2
* Module: menu

## Bug description

On small screens Top Navigation component doesn't behave correctly. The goal is to make it as fluid as Sidebar Navigation and
create consistency between two components by adding the topRightAction prop which will make the usage of these two components similar.

### Related issue

Closes #36

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added a story to cover my changes
- [x] All new and existing story tests pass

### CODE REVIEW

File: libs/menu/src/TopNavigation.tsx [hunk 1]
```diff
@@ -514,7 +543,7 @@ export function TopNavigationDropdown({
           <div className="px-2">{children}</div>
         </DropdownMenu>
       </div>
-      <div className={`md:hidden flex flex-col ${opened && "w-80"}`}>
+      <div className={`md:hidden flex flex-col ${opened ? "w-full" : "pl-14"}`}>
```
Comment (ivam5) [inline libs/menu/src/TopNavigation.tsx:546]: Is pl-14 actually necessary?

File: libs/menu/src/TopNavigation.tsx [hunk 2]
```diff
@@ -51,6 +51,14 @@ export type TopNavigationProps = {
    */
   logo?: React.ReactNode;
 
+  /**
+   * Actions defined on the right top side of the Top Navigation.
+   * Needs a 'Router' component as a wrapper, and it's preferred to use 'SidebarNavigation.Dropdown'
```
Comment (ivam5) [inline libs/menu/src/TopNavigation.tsx:56]: SidebarNavigation.Dropdown or TopNavigation.Dropdown?

**Review by ivam5 — CHANGES_REQUESTED** [review]

File: libs/menu/src/TopNavigation.tsx (hunk 1 above)
Comment (fbeceic) [reply libs/menu/src/TopNavigation.tsx:546]: Yes, otherwise the button stretches too much on mobile display. This way it has normal width and looks the same as SidebarNavigation's equivalent on mobile devices.

File: libs/menu/src/TopNavigation.tsx (hunk 2 above)
Comment (fbeceic) [reply libs/menu/src/TopNavigation.tsx:56]: Oops.

File: libs/menu/src/TopNavigation.tsx (hunk 1 above)
Comment (ivam5) [reply libs/menu/src/TopNavigation.tsx:546]: image
It seems strange and different from SidebarNavigation.

File: libs/menu/src/DropdownMenu.tsx [hunk 3]
```diff
@@ -133,7 +133,11 @@ function DropdownMenu({
   const responsiveIcon = (
     <div>
       <DropdownContext.Consumer>
-        {({ isExpanded }) => (isExpanded ? finalCloseExpanderIcon : finalOpenExpanderIcon)}
+        {({ isExpanded }) =>
+          isExpanded
+            ? React.cloneElement(finalCloseExpanderIcon, { className: iconClassName })
+            : React.cloneElement(finalOpenExpanderIcon, { className: iconClassName })
```
Comment (ivam5) [inline libs/menu/src/DropdownMenu.tsx:139]: Are you sure about this? It works fine without cloneElement if you pass the override.

**Review by ivam5 — APPROVED** [review]

**Review by jtomic-croz — APPROVED** [review]
