### PR TITLE
#193 Fix Select and Autocomplete (multiple selection) input references

### LINKED ISSUE #193: Incorrect input refs on Select and Autocomplete
## Basic information

* Tiller version: 1.8.0
* Module: formik-elements

## Bug description

The current implementation of the scroll-to-error feature (#167) does not properly handle errors occurring in `Select` and `Autocomplete (with multiple selection)` components. When validation errors are triggered in these components, the scroll-to-error functionality fails to scroll the viewport to the respective error messages, causing usability issues for users. This is because the reference to inputs in these components is incorrect, so the feature can't find an element to put into focus.

### PR DESCRIPTION
**Pull request by fbeceic**
## Basic information

* Tiller version: 1.8.0
* Module: selectors

## Description

Fixed non-existent `name` attribute on `Select` component which allows the `useScrollToError` hook to catch the element for error detection.
Fixed `Autocomplete` (multiple selection) input styling from `hidden` to `w-0 h-0 `so that the element exists and can be found by the hook.

### Related issue

Closes #193 

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added a story to cover my changes
- [x] All new and existing story tests pass

### CODE REVIEW

File: libs/selectors/src/Autocomplete.tsx [hunk 1]
```diff
@@ -986,7 +986,7 @@ function Autocomplete<T extends {}>({
         })}
         {...getComboboxProps({}, { suppressRefError: true })}
       />
-      {allowMultiple && <input type="hidden" name={name} />}
+      {allowMultiple && <input className="absolute w-0 h-0" name={name} />}
```
Comment (jtomic-croz) [inline libs/selectors/src/Autocomplete.tsx:989]: why type hidden doesn't work? it should still be in DOM and visible to JS. This seems to me that you're maybe focusing a wrong element with the helper hook

Comment (fbeceic) [reply libs/selectors/src/Autocomplete.tsx:989]: I thought the same, but for some reason when `type="hidden"` it's not found in the DOM. With this workaround it works as expected.

**Review by jtomic-croz — APPROVED** [review]
