### PR TITLE
Fix CheckboxGroupField & RadioGroupField error handling

### LINKED ISSUE #184: Checkbox group and radio group validation
## Basic information

* Tiller version:
1.7.4

* Module:
- Checkbox group: https://croz-ltd.github.io/tiller/?path=/docs/component-library-form-elements-checkboxgroup--simple
- Radio button group: https://croz-ltd.github.io/tiller/?path=/docs/component-library-form-elements-radiogroup--simple

## Bug description

When validation is made via front on any required field, every field looks neutral except checkbox and radio button group selection.

Example:  Fields "Ime" and "Prezime" are required, and so is "Spol" but only Spol field gets the validation message "Polje je obavezno" (Field is obligatory). 

image

### Steps to reproduce

1. Set validation for every obligatory field

### Expected behavior

should look like this:

image

### Actual behavior

looks like this:

image

### PR DESCRIPTION
**Pull request by fbeceic**
## Basic information

* Tiller version: 1.8.0
* Module: formik-elements

## Description

Fix inconsistent error detection & premature validation error display for the following components:
-  CheckboxGroupField 
- RadioGroupField

### Related issue

Closes #184

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added a story to cover my changes
- [x] All new and existing story tests pass

### CODE REVIEW

File: libs/formik-elements/src/RadioGroupField.tsx [hunk 1]
```diff
@@ -30,14 +31,25 @@ type RadioGroupFieldItemProps = RadioGroupItemProps;
 function RadioGroupField({ name, children, ...props }: RadioGroupFieldProps) {
   const [field, meta, helpers] = useField(name);
   const shouldValidate = useShouldValidate();
+  const initialError = useFormikBypass(name);
+
+  const onChange = (value: string | boolean | null) => {
+    helpers.setValue(value, shouldValidate);
+    initialError.current = undefined;
```
Comment (jtomic-croz) [inline libs/formik-elements/src/RadioGroupField.tsx:38]: are we doing this everywhere or just here?

Comment (fbeceic) [reply libs/formik-elements/src/RadioGroupField.tsx:38]: Everywhere, on every field component

**Review by jtomic-croz — APPROVED** [review]
