### PR TITLE
#15 Fix Progress Bar step margin

### LINKED ISSUE #15: Progress Bar - completed icon and sizing
## Basic information

* Tiller version: 1.0.1

* Module: core

## Bug description

Progress Bar component behaves strange when a lot of steps are defined, margins and padding are off and need to 
be adjusted.
Also, completed check icon is not rendering properly.

### Expected behavior

Appropriate padding on the left and right sides of the step. Check icon present when step is completed.

### Actual behavior

Inconsistent padding on the left and right sides of a step. Left size padding behaves normally but right padding is inconsistent.
Completed step is colored blue and check icon is not rendering inside it.

### PR DESCRIPTION
**Pull request by fbeceic**
## Basic information

* Tiller version: 1.0.1
* Module: menu

## Bug description

Progress Bar component behaves strange when a lot of steps are defined, margins and padding are off and need to
be adjusted.

### Related issue

Closes #15 

## Checklist

- [x] I have read the project's **CONTRIBUTING** document
- [x] I have checked my code with the project's static analysis tooling
- [x] I have formatted my code with the project's Prettier code-style configuration
- [x] I have checked my code for misspellings
- [x] I have organized my changes in easy-to-follow commits
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added a story to cover my changes
- [x] All new and existing story tests pass

### CODE REVIEW

File: libs/theme/src/defaultTheme.tsx [hunk 1]
```diff
@@ -1253,6 +1253,7 @@ const defaultComponentConfig = {
     stepContainer: {
       master: "flex items-center space-x-4",
       padding: "py-4 px-6",
+      margin: "mr-1",
```
Comment (ivam5) [inline libs/theme/src/defaultTheme.tsx:1256]: Why this margin? It looks fine without it.

Comment (fbeceic) [reply libs/theme/src/defaultTheme.tsx:1256]: It is required to fill in the width `w-1` of the separator. Small difference but provides better symmetry.

**Review by ivam5 — APPROVED** [review]

**Review by jtomic-croz — APPROVED** [review]
